version: '3.5'
services:
  config-service:
    container_name: config-service
    build: config-service
    ports:
      - "8001:8001"

  registry:
    container_name: registry
    restart: always
    build: registry
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
      - "8989:8989"
    depends_on:
      - config-service
      - registry

  account-service:
    restart: on-failure
    container_name: account-service
    build: account-service
    ports:
      - "8081:8081"
    depends_on:
      - config-service
      - registry
      - account-service-db

  account-service-db:
    container_name: account-service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_service_db
    ports:
      - "5431:5431"
    expose:
      - "5431"

  bill-service:
    restart: on-failure
    container_name: bill-service
    build: bill-service
    ports:
      - "8082:8082"
    depends_on:
      - config-service
      - registry
      - bill-service-db

  bill-service-db:
    container_name: bill-service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bill_service_db
    ports:
      - "5432:5432"
    expose:
      - "5432"

  deposit-service:
    restart: on-failure
    container_name: deposit-service
    build: deposit-service
    ports:
      - "8083:8083"
    depends_on:
      - config-service
      - registry
      - deposit-service-db

  deposit-service-db:
    container_name: deposit-service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deposit_service_db
    ports:
      - "5433:5433"
    expose:
      - "5433"

  notification-service:
    restart: on-failure
    container_name: notification-service
    build: notification-service
    depends_on:
      - config-service
      - registry

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - config-service
      - registry
      - account-service
