spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://account-service-db:5431/account_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /accounts
  port: 8081